name: quickbitev3
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  fluttertoast: ^8.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1
  uuid: ^4.2.1
  google_maps_flutter: ^2.11.0
  intl: ^0.20.2
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/  # Add this line for SVG files
  fonts:
    - family: Boxing
      fonts:
        - asset: assets/Fonts/OTF/Boxing-Regular.otf
    # If you want to use Google Fonts instead of local fonts, you can remove this section
    # and rely on the google_fonts package
